evidence_dir: "evidence"
study_dir: "studies"
study:
    "001":
        description: "study_description"
        preprocessor_module: "001.preprocessor"
        runner_module: "001.runner"
        postprocessor_module: "001.postprocessor"
        significant_sample_size: 30
    "002":
        description: "RegExEval: Evaluating Generated Regular Expressions and their Proneness to DoS Attacks"
        preprocessor_module: "002.preprocessor"
        runner_module: "002.runner"
        postprocessor_module: "002.postprocessor"
        significant_sample_size: 30
        source_dir: ""
        docker_image_name: "002:latest"
        use_kubernetes: false
    "003":
        description: "An Empirical Study on Compliance with Ranking Transparency in the Software Documentation of EU Online Platforms"
        preprocessor_module: "003.preprocessor"
        runner_module: "003.runner"
        postprocessor_module: "003.postprocessor"
        significant_sample_size: 30
        source_docker_file: "francescosovrano/dox4p2bcompliance:latest"
        docker_image_name: "003:latest"
    "005":
        description: "Demonstration-Free: Towards More Practical Log Parsing with Large Language Models"
        preprocessor_module: "005.preprocessor"
        runner_module: "005.runner"
        postprocessor_module: "005.postprocessor"
        significant_sample_size: 30
        source_dir: "replicationpackage"
        docker_image_name: "005:latest"
    "007":
        description: "Large Language Model for Vulnerability Detection"
        preprocessor_module: "007.preprocessor"
        runner_module: "007.runner"
        postprocessor_module: "007.postprocessor"
        significant_sample_size: 30
        source_dir: "ChatGPT_exp"
        docker_image_name: "007:latest"
    "009":
        description: "Lost in Translation: A Study of Bugs Introduced by Large Language Models while Translating Code"
        preprocessor_module: "009.preprocessor"
        runner_module: "009.runner"
        postprocessor_module: "009.postprocessor"
        significant_sample_size: 30
        source_dir: "replicationpackage"
        source_files: "https://github.com/Intelligent-CAT-Lab/PLTranslationEmpirical.git"
        data_files: "https://zenodo.org/records/10447705/files/dataset.zip?download=1"
        docker_image_name: "009:latest"
    "main2":
        description: "CrashTranslator: Automatically Reproducing Mobile Application Crashes Directly from Stack Trace"
        preprocessor_module: "main2.preprocessor"
        runner_module: "main2.runner"
        postprocessor_module: "main2.postprocessor"
        significant_sample_size: 30
        source_dir: "replicationpackage"
        source_files: "https://github.com/wuchiuwong/CrashTranslator.git"
    "main19":
        description: "Large Language Models are Few-Shot Summarizers: Multi-Intent Comment Generation via In-Context Learning"
        preprocessor_module: "main19.preprocessor"
        runner_module: "main19.runner"
        postprocessor_module: "main19.postprocessor"
        significant_sample_size: 30
        source_dir: "replicationpackage"
        source_files: "https://github.com/gmy2013/LLM_Comment_Generation.git"
        docker_image_name: "main19:latest"
    "main41":
        description: Automatic Semantic Augmentation of Language Model Prompts for Code Summarization
        preprocessor_module: "main41.preprocessor"
        runner_module: "main41.runner"
        postprocessor_module: "main41.postprocessor"
        significant_sample_size: 30
        source_dir: "replicationpackage"
        source_files: "https://zenodo.org/api/records/10494170/files-archive"
        docker_image_name: "main41:latest"
