evidence_dir: "evidence"
study_dir: "studies"
study:
    "001":
        description: "study_description"
        preprocessor_module: "001.preprocessor"
        runner_module: "001.runner"
        postprocessor_module: "001.postprocessor"
        significant_sample_size: 30
    "002":
        description: "RegExEval: Evaluating Generated Regular Expressions and their Proneness to DoS Attacks"
        preprocessor_module: "002.preprocessor"
        runner_module: "002.runner"
        postprocessor_module: "002.postprocessor"
        significant_sample_size: 30
        source_dir: "replicationpackage"
        docker_image_name: "002:latest"
    "009":
        description: "Lost in Translation: A Study of Bugs Introduced by Large Language Models while Translating Code"
        preprocessor_module: "009.preprocessor"
        runner_module: "009.runner"
        postprocessor_module: "009.postprocessor"
        significant_sample_size: 30
        source_dir: "replicationpackage"
        source_files: "https://github.com/Intelligent-CAT-Lab/PLTranslationEmpirical.git"
        data_files: "https://zenodo.org/records/10447705/files/dataset.zip?download=1"
        docker_image_name: "009:latest"
