evidence_dir: "evidence"
study_dir: "studies"
study:
  "001":
    description: "study_description"
    preprocessor_module: "001.preprocessor"
    runner_module: "001.runner"
    postprocessor_module: "001.postprocessor"
    significant_sample_size: 30
  "009":
    description: "Lost in Translation: A Study of Bugs Introduced by Large Language Models while Translating Code"
    preprocessor_module: "009.preprocessor"
    runner_module: "009.runner"
    postprocessor_module: "009.postprocessor"
    significant_sample_size: 30
    source_dir: "replicationpackage"
    source_files: "https://github.com/Intelligent-CAT-Lab/PLTranslationEmpirical.git"
    data_files: "https://zenodo.org/records/10447705/files/dataset.zip?download=1"
    docker_image_name: "009:latest"
  "main2":
    description: "CrashTranslator: Automatically Reproducing Mobile Application Crashes Directly from Stack Trace"
    preprocessor_module: "main2.preprocessor"
    runner_module: "main2.runner"
    postprocessor_module: "main2.postprocessor"
    significant_sample_size: 30
    source_dir: "replicationpackage"
    source_files: "https://github.com/wuchiuwong/CrashTranslator.git"
  "main19":
    description: "Large Language Models are Few-Shot Summarizers: Multi-Intent Comment Generation via In-Context Learning"
    preprocessor_module: "main19.preprocessor"
    runner_module: "main19.runner"
    postprocessor_module: "main19.postprocessor"
    significant_sample_size: 30
    source_dir: "replicationpackage"
    source_files: "https://github.com/gmy2013/LLM_Comment_Generation.git"
    docker_image_name: "main19:latest"
